/**
 * 错误码
 *
 * @author kejunyao
 * @since 2020年05月30日
 */

#ifndef AUDIOPLAYER_ERRORCODE_H
#define AUDIOPLAYER_ERRORCODE_H

#define ERROR_AV_FORMAT_OPEN_INPUT        1
#define ERROR_AV_STREAM_FORMAT_NOT_FOUND  2
#define ERROR_AV_MEDIA_TYPE_NOT_FOUND     3
#define ERROR_AV_CODEC_DECODER_NOT_FOUND  4
#define ERROR_AV_CODEC_ALLOC_CONTEXT3     5
#define ERROR_AV_CODEC_PARAMETERS_CONTEXT 6
#define ERROR_AV_CODEC_OPEN2              7

#endif //AUDIOPLAYER_ERRORCODE_H
